apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  nodeSelector: 
    size: Large  #kc label node node2 size=Large
  containers:
  - name: myapp
    image: nginx
    resources:
      # limits:
      #   memory: "128Mi"
      #   cpu: "500m"
    ports:
      - containerPort: 8080
