apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-schedule
  name: pod-schedule
spec:
  nodeName: node2
  containers:
  - image: nginx
    name: pod-schedule
    command:
      - sleep
      - "3600"
    ports:
    - name:  portname
      containerPort:  8080
    
      

