FROM  openjdk:8-jre-alpine
WORKDIR /app 
COPY demo-0.0.1-SNAPSHOT.jar demo-0.0.1-SNAPSHOT.jar
#COPY demo-0.0.1-SNAPSHOT.jar /app/demo-0.0.1-SNAPSHOT.jar
#RUN java -jar /app/demo-0.0.1-SNAPSHOT.jar
#CMD ["java", "-version"]
CMD [ "java", "-jar", "demo-0.0.1-SNAPSHOT.jar" ]
