apiVersion: batch/v1
kind: Job
metadata:
  name:  counter
  namespace: chander
spec:
  template:
    metadata:
      name:  counter
    spec:
      containers:
      - name:  counter
        image:  busybox        
        command:
          - "sh"
          - "-c"
          - "seq 100 | while read i; do echo $i;sleep 5; done"
      restartPolicy: Never        