apiVersion: apps/v1
kind: Deployment
metadata:
 name: myapp-deploy
 labels:
  app: myapp
  type: front-end
spec:
 template:
  metadata:
    name: spec-myapp-deploy
    labels:
      app: myapp
      type: front-end
  spec:
    containers:
      - image:  nginx
        name:  nginx-rs
 replicas: 2
 selector:
  matchLabels:
   type: front-end


## IT will delete RS if it already exists
#
## To scale further
# Either
#   change the YAML and use KC replace -f a.yaml
# or
#   kc scale --replicas=6 -f a.yaml
# or 
#   kc scale --replicasa=6  deploy myapp-deploy

## You still need tempalte definition for the container definition