apiVersion: v1
kind: Service
metadata:
  name:  clusterip-svc
spec:
  selector: ## get it from pods, or deployment 
    app:  tbd
    env: dev
  type:   ClusterIP #LoadBalancer # || NodePort
  ports:
  - name:  name-of-the-port
    port:  80
    targetPort:  8080