apiVersion: v1
kind: Service
metadata:
  name:  nodeport-svc
spec:
  selector: ## get it from pods, or deployment 
    app:  tbd
    env: dev
  type:  NodePort #LoadBalancer # | ClusterIP | NodePort
  ports:
  - name:  name-of-the-port
    port:  80
    targetPort:  8080
    nodePort: 30008 #optionl