apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
spec:
  volumes:
    - name:  task-pv-storage
      persistentVolumeClaim:
          claimName: task-pv-claim
  containers:
    - image:  nginx
      name:  task-pv-container
      ports:
      - name:  "http-server"
        containerPort:  80
      volumeMounts:
        - name:  task-pv-storage
          mountPath:  "/usr/share/nginx/html"