apiVersion: v1
kind: PersistentVolume
metadata: 
 name: task-pv-volume
 labels:
  type: local
spec:
 storageClassName: manual
 capacity:
  storage: 100Ki
 accessModes:
  - ReadWriteOnce
 hostPath:
   path: "/opt"