---
- name: from https://www.linkedin.com/pulse/how-kubernetes-yourself-kubeadm-ansible-vagrant-michele-sciabarr%C3%A0/
  hosts: nodes
  tasks:
  #  -command: modprobe {{item}}
  #   with_items:    
  #     - ip_vs
  #     - ip_vs_rr
  #     - ip_vs_wrr
  #     - ip_vs_sh
  #     - nf_conntrack_ipv4    
  #  - name : Lineinfile
  #    lineinfile: path=/etc/modules line='{{item}}' create=yes state=present
  #    with_items: 
  #    - ip_vs
  #    - ip_vs_rr
  #    - ip_vs_wrr
  #    - ip_vs_sh
  #    - nf_conntrack_ipv4
    - sysctl: name=net.ipv4.ip_forward value=1 state=present reload=yes sysctl_set=yes
    - service: name=docker state=started enabled=yes
    - service: name=ntp state=started enabled=yes
    - service: name=kubelet state=started enabled=yes
...
