---
- name:  Install packages
  hosts: all
  tasks:
   - name : Start basic 
     shell: "apt-get -y update && apt-get install -y apt-transport-https screen sysstat tcpdump curl wget"
   - name : packages
     apt: name={{ item }}  state=absent
     with_items:
       - docker.io
       - kubelet
       - kubeadm
       - kubectl
   - name : packages
     apt: name={{ item }}  state=present
     with_items:
       - docker.io
       - kubelet
       - kubeadm
       - kubectl
       - ntp
       - iptables
       - arptables
       - ebtables
       - curl 
       - wget 
       - sysstat
       - tcpdump
       - bash-completion
   - name : enableva
     service: name=docker enabled=yes state=started
...


