kind: Service
apiVersion: v1
metadata:
  name:  webapp-sql1
spec:
  selector:
    app:  webapp-sql
    tier: backend
  # type:  LoadBalancer | ClusterIP | NodePort
  clusterIP: None
  ports:
  - name:  name-of-the-port
    port:  3306